apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemonset
  labels:
    name: monitoring-daemonset
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
        name: monitoring-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
            name: http-port
