apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-quota
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 10Gi
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
status: {}
