apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    name: my-app
    type: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: my-app-pod
      labels:
        name: my-app-pod
        type: frontend
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
          - containerPort: 80
