apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp-nodeport
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
