apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp-lb
spec:
  ports:
  - port: 82
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: LoadBalancer
status:
  loadBalancer: {}
